version: '3'
services:
  web:
    build:
      context: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000"
    ports:
      - '3000:3000'
    environment:
      POSTGRES_DB: "square_development"
      POSTGRES_PASSWORD: "password"
      POSTGRES_USERNAME: "square"
    links:
      - db
  db:
    image: postgres:14.8
    ports:
      - "5432:5432"
